(function(){var h={},mt={},c={id:"08d82327f89d52d81d65805b65e7c28d",dm:["mjwatch.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[{id:"html%3ebody%3ep%3ei",eventType:"onclick"},{id:"html%3ebody%3ediv%5b3%5d%3ediv%5b5%5d%3ediv%5b1%5d%3ediv%5b1%5d%3espan%5b1%5d",eventType:"onclick"},{id:"html%3ebody%3ediv%5b3%5d%3ediv%5b5%5d%3ediv%5b1%5d%3ediv%5b2%5d%3espan%5b1%5d",eventType:"onclick"},{id:"%23tabnav%3eul%3eli%5b2%5d",eventType:"onclick"},{id:"html%3ebody%3ediv%5b3%5d%3ediv%5b5%5d%3ep%5b2%5d%3eimg",eventType:"onclick"},{id:"html%3ebody%3ediv%5b3%5d%3ediv%5b1%5d%3ediv%3ea",eventType:"onclick"}],cetrk:[],icon:'',ctrk:true,align:0,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:13109170,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,aet:'',hca:'F75A7FBEB6A26451',conv:0,med:0,cvcc:'',cvcf:[],apps:'siteId=13109170&mapCardId=28304'};var s=void 0,u=!0,w=null,x=!1;mt.cookie={};mt.cookie.set=function(b,a,e){var d;e.P&&(d=new Date,d.setTime(d.getTime()+e.P));document.cookie=b+"="+a+(e.domain?"; domain="+e.domain:"")+(e.path?"; path="+e.path:"")+(d?"; expires="+d.toGMTString():"")+(e.xc?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:w};
mt.cookie.Xb=function(b,a){try{var e="Hm_ck_"+ +new Date;mt.cookie.set(e,"is-cookie-enabled",{domain:b,path:a,P:s});var d="is-cookie-enabled"===mt.cookie.get(e)?"1":"0";mt.cookie.set(e,"",{domain:b,path:a,P:-1});return d}catch(f){return"0"}};mt.lang={};mt.lang.e=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};mt.lang.ya=function(b){return mt.lang.e(b,"Number")&&isFinite(b)};mt.lang.fa=function(b){return mt.lang.e(b,"String")};
mt.lang.g=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.K=function(b,a){var e=x;if(b==w||!mt.lang.e(b,"Array")||a===s)return e;if(Array.prototype.indexOf)e=-1!==b.indexOf(a);else for(var d=0;d<b.length;d++)if(b[d]===a){e=u;break}return e};
(function(){var b=mt.lang;mt.f={};mt.f.aa=function(a){return document.getElementById(a)};mt.f.Bb=function(a){if(!a)return w;try{a=String(a);if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var b=a.split(">"),d=document.body,f=b.length-1;0<=f;f--)if(-1<b[f].indexOf("#")){var g=b[f].split("#")[1];(d=document.getElementById(g))||(d=document.getElementById(decodeURIComponent(g)));b=b.splice(f+1,b.length-(f+1));break}for(a=0;d&&a<b.length;){var m=String(b[a]).toLowerCase();
if(!("html"===m||"body"===m)){var f=0,l=b[a].match(/\[(\d+)\]/i),g=[];if(l)f=l[1]-1,m=m.split("[")[0];else if(1!==d.childNodes.length){for(var p=0,t=0,v=d.childNodes.length;t<v;t++){var q=d.childNodes[t];1===q.nodeType&&q.nodeName.toLowerCase()===m&&p++;if(1<p)return w}if(1!==p)return w}for(p=0;p<d.childNodes.length;p++)1===d.childNodes[p].nodeType&&d.childNodes[p].nodeName.toLowerCase()===m&&g.push(d.childNodes[p]);if(!g[f])return w;d=g[f]}a++}return d}catch(r){return w}};mt.f.ua=function(a,b){var d=
[],f=[];if(!a)return f;for(;a.parentNode!=w;){for(var g=0,m=0,l=a.parentNode.childNodes.length,p=0;p<l;p++){var t=a.parentNode.childNodes[p];if(t.nodeName===a.nodeName&&(g++,t===a&&(m=g),0<m&&1<g))break}if((l=""!==a.id)&&b){d.unshift("#"+encodeURIComponent(a.id));break}else l&&(l="#"+encodeURIComponent(a.id),l=0<d.length?l+">"+d.join(">"):l,f.push(l)),d.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<g?"["+m+"]":""));a=a.parentNode}f.push(d.join(">"));return f};mt.f.Na=function(a){return(a=
mt.f.ua(a,u))&&a.length?String(a[0]):""};mt.f.Ib=function(a){return mt.f.ua(a,x)};mt.f.yb=function(a){var b;for(b="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return w};mt.f.Ab=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Gb=function(a){var b={top:0,left:0};if(!a)return b;var d=mt.f.Ab(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());return{top:b.top+(window.pageYOffset||d.scrollTop)-(d.clientTop||0),left:b.left+
(window.pageXOffset||d.scrollLeft)-(d.clientLeft||0)}};mt.f.getAttribute=function(a,b){var d=a.getAttribute&&a.getAttribute(b)||w;if(!d&&a.attributes&&a.attributes.length)for(var f=a.attributes,g=f.length,m=0;m<g;m++)f[m].nodeName===b&&(d=f[m].nodeValue);return d};mt.f.ca=function(a){var b="document";a.tagName!==s&&(b=a.tagName);return b.toLowerCase()};mt.f.Kb=function(a){var e="";a.textContent?e=b.trim(a.textContent):a.innerText&&(e=b.trim(a.innerText));e&&(e=e.replace(/\s+/g," ").substring(0,255));
return e};mt.f.La=function(a,e){var d=mt.f.ca(a);"input"===d&&e&&("button"===a.type||"submit"===a.type)?d=b.trim(a.value)||"":"input"===d&&!e&&"password"!==a.type?d=b.trim(a.value)||"":"img"===d?(d=mt.f.getAttribute,d=d(a,"alt")||d(a,"title")||d(a,"src")):d="body"===d||"html"===d?["(hm-default-content-for-",d,")"].join(""):mt.f.Kb(a);return String(d).substring(0,255)};(function(){(mt.f.Ta=function(){function a(){if(!a.ea){a.ea=u;for(var d=0,b=f.length;d<b;d++)f[d]()}}function b(){try{document.documentElement.doScroll("left")}catch(d){setTimeout(b,
1);return}a()}var d=x,f=[],g;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,x);a()}:document.attachEvent&&(g=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",g),a())});(function(){if(!d)if(d=u,"complete"===document.readyState)a.ea=u;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,x),window.addEventListener("load",a,x);else if(document.attachEvent){document.attachEvent("onreadystatechange",
g);window.attachEvent("onload",a);var f=x;try{f=window.frameElement==w}catch(l){}document.documentElement.doScroll&&f&&b()}})();return function(d){a.ea?d():f.push(d)}}()).ea=x})();return mt.f})();mt.event={};mt.event.d=function(b,a,e){b.attachEvent?b.attachEvent("on"+a,function(a){e.call(b,a)}):b.addEventListener&&b.addEventListener(a,e,x)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=x};
(function(){var b=mt.event;mt.h={};mt.h.xa=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.h.Eb=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.h.cookieEnabled=navigator.cookieEnabled;mt.h.javaEnabled=navigator.javaEnabled();mt.h.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.h.fc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.h.colorDepth=
window.screen.colorDepth||0;mt.h.S=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.h.J=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.h.orientation=0;(function(){function a(){var a=0;window.orientation!==s&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==s)&&(a=screen.orientation.angle);mt.h.orientation=
a}a();b.d(window,"orientationchange",a)})();return mt.h})();mt.s={};mt.s.parse=function(b){return(new Function("return ("+b+")"))()};
mt.s.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=e[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var e={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return b(d);case "boolean":return String(d);
default:if(d===w)return"null";if(d instanceof Array){var f=["["],g=d.length,e,l,p;for(l=0;l<g;l++)switch(p=d[l],typeof p){case "undefined":case "function":case "unknown":break;default:e&&f.push(","),f.push(mt.s.stringify(p)),e=1}f.push("]");return f.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+a(d.getMonth()+1)+"-"+a(d.getDate())+"T"+a(d.getHours())+":"+a(d.getMinutes())+":"+a(d.getSeconds())+'"';e=["{"];l=mt.s.stringify;for(g in d)if(Object.prototype.hasOwnProperty.call(d,g))switch(p=
d[g],typeof p){case "undefined":case "unknown":case "function":break;default:f&&e.push(","),f=1,e.push(l(g)+":"+l(p))}e.push("}");return e.join("")}}}();mt.localStorage={};mt.localStorage.la=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(b){return x}return u};
mt.localStorage.set=function(b,a,e){var d=new Date;d.setTime(d.getTime()+e||31536E6);try{window.localStorage?(a=d.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.la()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(b,a),mt.localStorage.l.save(document.location.hostname))}catch(f){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),e=b.substring(0,a)-0;if(e&&e>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.la())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(b)}catch(d){}return w};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.la())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(b),mt.localStorage.l.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){try{window.sessionStorage&&window.sessionStorage.setItem(b,a)}catch(e){}};
mt.sessionStorage.get=function(b){try{return window.sessionStorage?window.sessionStorage.getItem(b):w}catch(a){return w}};mt.sessionStorage.remove=function(b){try{window.sessionStorage&&window.sessionStorage.removeItem(b)}catch(a){}};mt.Ya={};mt.Ya.log=function(b,a){var e=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=e;e.onload=function(){e.onload=w;e=window[d]=w;a&&a(b)};e.src=b};mt.Da={};
mt.Da.Lb=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(e){}return b};
mt.Da.uc=function(b,a,e,d,f){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+e+'" height="'+d+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(f||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+e+'" height="'+d+'" src="'+a+'" flashvars="'+(f||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.o=function(b,a){var e=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return e?e[3]:w};mt.url.vc=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:w};mt.url.Db=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):w};mt.url.R=function(b){return(b=mt.url.Db(b))?b.replace(/:\d+$/,""):b};mt.url.ua=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):w};
(function(){function b(){for(var a=x,b=document.getElementsByTagName("script"),d=b.length,d=100<d?100:d,f=0;f<d;f++){var g=b[f].src;if(g&&0===g.indexOf("https://hm.baidu.com/h")){a=u;break}}return a}return h.wb=b})();var A=h.wb;
h.m={Tb:"http://tongji.baidu.com/hm-web/welcome/ico",Ca:"hm.baidu.com/hm.gif",gb:/^(tongji|hmcdn).baidu.com$/,$a:"tongji.baidu.com",Qb:"hmmd",Rb:"hmpl",qc:"utm_medium",Pb:"hmkw",sc:"utm_term",Nb:"hmci",pc:"utm_content",Sb:"hmsr",rc:"utm_source",Ob:"hmcu",oc:"utm_campaign",L:0,H:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ha:A()||"https:"===document.location.protocol?"https:":"http:",wc:0,ob:6E5,Yb:6E5,gc:5E3,pb:5,N:1024,nb:1,M:2147483647,Za:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn p ct u tt hh".split(" "),
T:u,Ja:["a","input","button"],ib:{id:"data-hm-id",qa:"data-hm-class",Ga:"data-hm-xpath",content:"data-hm-content",Ea:"data-hm-tag",link:"data-hm-link"},Ia:"data-hm-enabled",Ha:"data-hm-disabled",bc:"https://hmcdn.baidu.com/static/tongji/plugins/",Sa:["UrlChangeTracker"]};(function(){var b={C:{},d:function(a,b){this.C[a]=this.C[a]||[];this.C[a].push(b)},I:function(a,b){this.C[a]=this.C[a]||[];for(var d=this.C[a].length,f=0;f<d;f++)this.C[a][f](b)}};return h.w=b})();
(function(){function b(b,d){var f=document.createElement("script");f.charset="utf-8";a.e(d,"Function")&&(f.readyState?f.onreadystatechange=function(){if("loaded"===f.readyState||"complete"===f.readyState)f.onreadystatechange=w,d()}:f.onload=function(){d()});f.src=b;var g=document.getElementsByTagName("script")[0];g.parentNode.insertBefore(f,g)}var a=mt.lang;return h.load=b})();
(function(){function b(){var d="";if(h.c.b.nv){d=encodeURIComponent(document.referrer);try{window.sessionStorage?e.set("Hm_from_"+c.id,d):a.set("Hm_from_"+c.id,d,864E5)}catch(b){}}else try{d=(window.sessionStorage?e.get("Hm_from_"+c.id):a.get("Hm_from_"+c.id))||""}catch(g){}return d}var a=mt.localStorage,e=mt.sessionStorage;return h.xb=b})();
(function(){var b=h.m,a={init:function(){if(""!==c.icon){var a=c.icon.split("|"),d=b.Tb+"?s="+c.id,f="https://hmcdn.baidu.com/static"+a[0]+".gif";document.write("swf"===a[1]||"gif"===a[1]?'<a href="'+d+'" target="_blank"><img border="0" src="'+f+'" width="'+a[2]+'" height="'+a[3]+'"></a>':'<a href="'+d+'" target="_blank">'+a[0]+"</a>")}}};h.w.d("pv-b",a.init);return a})();
(function(){var b=mt.cookie,a=mt.localStorage,e=mt.sessionStorage,d={getData:function(d){try{return b.get(d)||e.get(d)||a.get(d)}catch(g){}},setData:function(f,g,m){try{b.set(f,g,{domain:d.Q(),path:d.ba(),P:m}),m?a.set(f,g,m):e.set(f,g)}catch(l){}},ec:function(f){try{b.set(f,"",{domain:d.Q(),path:d.ba(),P:-1}),e.remove(f),a.remove(f)}catch(g){}},U:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length===a.length},ga:function(a,d){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(d)},Q:function(){for(var a=document.location.hostname,b=0,e=c.dm.length;b<e;b++)if(d.U(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ba:function(){for(var a=0,b=c.dm.length;a<b;a++){var e=c.dm[a];if(-1<e.indexOf("/")&&d.ga(document.location.href,e))return e.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.ra=d})();
(function(){var b=mt.lang,a=mt.s,e=h.ra,d={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},f={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},g=["session","user"],m="Hm_up_"+c.id,l={init:function(){l.Vb()},Vb:function(){try{var f=a.parse(decodeURIComponent(e.getData(m)));b.e(f,"Object")&&(d.user=f)}catch(g){}},D:function(a){var b={};d[a]!==s&&(b=d[a]);a=this.va();for(var f in b)b.hasOwnProperty(f)&&(a[f]=b[f]);return a},va:function(){for(var a={},b,f=g.length-
1;0<=f;f--){b=d[g[f]];for(var q in b)b.hasOwnProperty(q)&&(a[q]=b[q])}return a},setProperty:function(f,g,e){var q=d[f];if(b.e(q,"Object")&&b.e(g,"Object")){for(var m in g)if(g.hasOwnProperty(m)){var k=b.g(String(m));if(e||!((/^_/.test(k)||/_$/.test(k))&&"_iden"!==k)){var n=g[m];if(n==w)delete q[k];else{if(b.e(n,"Object")||b.e(n,"Array"))n=a.stringify(n);n=b.g(String(n));l.Wb(f,k,n)&&(q[k]={value:n,scope:l.Oa(f)})}}}"user"===f&&l.Aa()}},z:function(a){a!==s&&("userId"===a&&b.e(d.user,"Object")?(delete d.user.uid_,
l.Aa()):"user"===a&&b.e(d.user,"Object")?(a=d.user.uid_,d.user=a===s?{}:{uid_:a},l.Aa()):d[a]!==s&&(d[a]={}))},Aa:function(){try{e.setData(m,encodeURIComponent(a.stringify(d.user)),c.age)}catch(b){}},Wb:function(a,b,f){var g=u,e=d[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(f)).length)g=x;else{var k=e[b];e[b]={value:f,scope:l.Oa(a)};a=l.X(l.D(a));2048<encodeURIComponent(a).length&&(k!==s?e[b]=k:delete e[b],g=x)}return g},X:function(a){var b=[],d,f;for(f in a)a.hasOwnProperty(f)&&
(d=[f,a[f].value],(1===a[f].scope||2===a[f].scope)&&d.push(a[f].scope),b.push(d.join("*")));return b.join("!")},Oa:function(a){a=f[a];return a!==s?a:f.others}};return h.Z=l})();
(function(){var b=mt.lang,a=mt.f,e={O:function(b,f){return function(g){var m=g.target||g.srcElement;if(m){var l=m.getAttribute(b.Y);g=g.clientX+":"+g.clientY;if(l&&l===g)m.removeAttribute(b.Y);else if(f&&0<f.length&&(m=a.Ib(m))&&m.length)if(l=m.length,g=m[m.length-1],1E4>l*g.split(">").length)for(g=0;g<l;g++)e.Xa(b,m[g]);else e.Xa(b,g)}}},Xa:function(a,f){for(var g={},e=String(f).split(">").length,l=0;l<e;l++)g[f]="",f=f.substring(0,f.lastIndexOf(">"));a&&(b.e(a,"Object")&&a.pa)&&a.pa(g)},Ua:function(a,
b){return function(g){(g.target||g.srcElement).setAttribute(a.Y,g.clientX+":"+g.clientY);a&&a.r&&(b?a.r(b):a.r("#"+encodeURIComponent(this.id),g.type))}}};return h.$=e})();
(function(){var b=mt.f,a=mt.event,e=h.$,d={Y:"HM_fix",oa:function(){a.d(document,"click",e.O(d,c.etrk));for(var f=c.etrk.length,g=0;g<f;g++){var m=c.etrk[g],l=decodeURIComponent(String(m.id));-1===l.indexOf(">")&&(0===l.indexOf("#")&&(l=l.substring(1)),(l=b.aa(decodeURIComponent(l)))&&a.d(l,m.eventType,e.Ua(d)))}},pa:function(a){if(c.etrk&&c.etrk.length)for(var b=c.etrk.length,e=0;e<b;e++){var l=decodeURIComponent(String(c.etrk[e].id));a.hasOwnProperty(l)&&d.r(l)}},r:function(a,b){h.c.b.et=1;h.c.b.ep=
"{id:"+a+",eventType:"+(b||"click")+"}";h.c.i()}};h.w.d("pv-b",d.oa);return d})();
(function(){var b=mt.f,a=mt.s,e=mt.event,d=mt.lang,f=h.$,g=h.Z,m=g.X,l={Y:"HM_ce",oa:function(){if(c.cetrk&&c.cetrk.length){e.d(document,"click",f.O(l,c.cetrk));for(var d=0,g=c.cetrk.length;d<g;d++){var m;try{m=a.parse(decodeURIComponent(String(c.cetrk[d])))}catch(q){m={}}var r=m.p||"";-1===r.indexOf(">")&&(0===r.indexOf("#")&&(r=r.substring(1)),(r=b.aa(r))&&e.d(r,"click",f.Ua(l,m)))}}},pa:function(b){if(c.cetrk&&c.cetrk.length)for(var d=0,f=c.cetrk.length;d<f;d++){var e;try{e=a.parse(decodeURIComponent(String(c.cetrk[d])))}catch(g){e=
{}}b.hasOwnProperty(e.p)&&l.r(e)}},r:function(a){h.c.b.et=7;var f=a&&a.k||"",f=d.g(f),e={};if(a&&a.a&&d.e(a.a,"Object"))for(var l in a.a)if(a.a.hasOwnProperty(l)){var r=b.Bb(a.a[l]||""),r=r?b.La(r,x):"";e[l]=r}e._iden=f;g.setProperty("customEvent",e);h.c.b.ep="";h.c.b.p=m(g.D("customEvent"));h.c.i();h.c.b.p="";g.z("customEvent")}};h.w.d("pv-b",l.oa);return l})();
(function(){var b=mt.f,a=mt.lang,e=mt.event,d=mt.h,f=h.m,g=h.w,m=[],l={ab:function(){c.ctrk&&(e.d(document,"mouseup",l.mb()),e.d(window,"unload",function(){l.ia()}),setInterval(function(){l.ia()},f.ob))},mb:function(){return function(a){a=l.zb(a);if(""!==a){var b=(f.ha+"//"+f.Ca+"?"+h.c.Wa().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(f.M+"").length>f.N||(b+encodeURIComponent(m.join("!")+(m.length?"!":"")).length+(f.M+"").length>f.N&&l.ia(),m.push(a),(m.length>=f.pb||/\*a\*/.test(a))&&
l.ia())}}},zb:function(e){var g=e.target||e.srcElement;if(0===f.nb){var m=(g.tagName||"").toLowerCase();if("embed"==m||"object"==m)return""}var r;d.xa?(r=Math.max(document.documentElement.scrollTop,document.body.scrollTop),m=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),m=e.clientX+m,r=e.clientY+r):(m=e.pageX,r=e.pageY);e=l.Fb(e,g,m,r);var k=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:m-=k/2;break;case 2:m-=k}k=
[];k.push(m);k.push(r);k.push(e.Zb);k.push(e.$b);k.push(e.dc);k.push(a.g(e.ac));k.push(e.tc);k.push(e.Mb);(g="a"===(g.tagName||"").toLowerCase()?g:b.yb(g))?(k.push("a"),k.push(a.g(encodeURIComponent(g.href)))):k.push("b");return k.join("*")},Fb:function(f,e,g,l){f=b.Na(e);var k=0,n=0,z=0,y=0;if(e&&(k=e.offsetWidth||e.clientWidth,n=e.offsetHeight||e.clientHeight,y=b.Gb(e),z=y.left,y=y.top,a.e(e.getBBox,"Function")&&(n=e.getBBox(),k=n.width,n=n.height),"html"===(e.tagName||"").toLowerCase()))k=Math.max(k,
e.clientWidth),n=Math.max(n,e.clientHeight);return{Zb:Math.round(100*((g-z)/k)),$b:Math.round(100*((l-y)/n)),dc:d.orientation,ac:f,tc:k,Mb:n}},ia:function(){0!==m.length&&(h.c.b.et=2,h.c.b.ep=m.join("!"),h.c.i(),m=[])}},p={eb:function(){c.ctrk&&setInterval(p.hc,f.gc)},hc:function(){var a=d.S()+d.J();0<a-h.c.b.vl&&(h.c.b.vl=a)}};g.d("pv-b",l.ab);g.d("pv-b",p.eb);return l})();
(function(){var b=mt.lang,a=mt.f,e=mt.event,d=mt.h,f=h.m,g=h.w,m=h.Z,l=m.X,p=+new Date,t=[],v={O:function(){return function(d){if(h.c&&h.c.T&&c.aet&&c.aet.length){var e=d.target||d.srcElement;if(e){var g=h.c.Ja,n=a.getAttribute(e,f.Ia)!=w?u:x;if(a.getAttribute(e,f.Ha)==w)if(n)v.ma(v.ta(e,d));else{var z=a.ca(e);if(b.K(g,"*")||b.K(g,z))v.ma(v.ta(e,d));else for(;e.parentNode!=w;){var n=e.parentNode,z=a.ca(n),y="a"===z&&b.K(g,"a")?u:x,z="button"===z&&b.K(g,"button")?u:x,G=a.getAttribute(n,f.Ia)!=w?u:
x;if(a.getAttribute(n,f.Ha)==w&&(y||z||G)){v.ma(v.ta(n,d));break}e=e.parentNode}}}}}},ta:function(e,g){var k={},n=f.ib;k.id=a.getAttribute(e,n.id)||a.getAttribute(e,"id")||"";k.qa=a.getAttribute(e,n.qa)||a.getAttribute(e,"class")||"";k.Ga=a.getAttribute(e,n.Ga)||a.Na(e);k.content=a.getAttribute(e,n.content)||a.La(e,u);k.Ea=a.getAttribute(e,n.Ea)||a.ca(e);k.link=a.getAttribute(e,n.link)||a.getAttribute(e,"href")||"";k.type=g.type||"click";n=b.ya(e.offsetTop)?e.offsetTop:0;"click"===g.type?n=d.xa?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.za&&b.e(g.za.changedTouches,"Array")&&g.za.changedTouches.length)&&(n=g.za.changedTouches[0].pageY);k.nc=n;return k},ma:function(a){var d=b.g;a=[+new Date-(h.c.F!==s?h.c.F:p),d(a.id),d(a.qa),d(a.Ea),d(a.Ga),d(a.link),d(a.content),a.type,a.nc].join("*");v.na(a);b.e(this.W(),"Function")&&this.W()()},na:function(a){a.length>f.N||(encodeURIComponent(t.join("!")+a).length>f.N&&(v.r(t.join("!")),t=[]),t.push(a))},
r:function(a){h.c.b.et=5;h.c.b.ep=a;h.c.b.p=l(m.D("autoEventTracking"));h.c.i();h.c.b.p=""},W:function(){return function(){t&&t.length&&(v.r(t.join("!")),t=[])}}};b.fa(c.aet)&&""!==c.aet&&g.d("pv-b",function(){e.d(document,"click",v.O());"ontouchend"in document&&e.d(window,"touchend",v.O());e.d(window,"unload",v.W())});return v})();
(function(){var b=mt.event,a=mt.h,e=h.m,d=h.w,f=+new Date,g=[],m=w,l={tb:function(){return function(){h.c&&(h.c.T&&c.aet&&c.aet.length)&&(window.clearTimeout(m),m=window.setTimeout(function(){l.cb(a.S()+a.J())},150))}},cb:function(a){l.na([+new Date-(h.c.F!==s?h.c.F:f),a].join("*"))},na:function(a){if(encodeURIComponent(g.join("!")+a).length>e.N||3<g.length)l.r(g.join("!")),g=[];g.push(a)},r:function(b){h.c.b.et=6;h.c.b.vh=a.J();h.c.b.ep=b;h.c.i()},W:function(){return function(){g&&g.length&&(l.r(g.join("!")),
g=[])}}};mt.lang.fa(c.aet)&&""!==c.aet&&d.d("pv-b",function(){b.d(window,"scroll",l.tb());b.d(window,"unload",l.W())});return l})();
(function(){var b=mt.f,a=h.m,e=h.load,d=h.xb;h.w.d("pv-b",function(){var f=a.protocol+"//crs.baidu.com/";c.rec&&b.Ta(function(){for(var g=0,m=c.rp.length;g<m;g++){var l=c.rp[g][0],p=c.rp[g][1],t=b.aa("hm_t_"+l);if(p&&!(2==p&&!t||t&&""!==t.innerHTML))t="",t=Math.round(Math.random()*a.M),t=4==p?f+"hl.js?"+["siteId="+c.id,"planId="+l,"rnd="+t].join("&"):f+"t.js?"+["siteId="+c.id,"planId="+l,"from="+d(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
t].join("&"),e(t)}})})})();
(function(){function b(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.sa.Hb()+","+h.sa.Cb();h.c.i()}}function a(){clearTimeout(y);var b;n&&(b="visible"==document[n]);z&&(b=!document[z]);l="undefined"==typeof b?u:b;if((!m||!p)&&l&&t)k=u,q=+new Date;else if(m&&p&&(!l||!t))k=x,r+=+new Date-q;m=l;p=t;y=setTimeout(a,100)}function e(a){var b=document,n="";if(a in b)n=a;else for(var d=["webkit","ms","moz","o"],e=0;e<d.length;e++){var y=d[e]+a.charAt(0).toUpperCase()+a.slice(1);if(y in b){n=
y;break}}return n}function d(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))t="focus"==b.type||"focusin"==b.type?u:x,a()}var f=mt.event,g=h.w,m=u,l=u,p=u,t=u,v=+new Date,q=v,r=0,k=u,n=e("visibilityState"),z=e("hidden"),y;a();(function(){var b=n.replace(/[vV]isibilityState/,"visibilitychange");f.d(document,b,a);f.d(window,"pageshow",a);f.d(window,"pagehide",a);"object"==typeof document.onfocusin?(f.d(document,"focusin",d),f.d(document,"focusout",d)):(f.d(window,"focus",d),
f.d(window,"blur",d))})();h.sa={Hb:function(){return+new Date-v},Cb:function(){return k?+new Date-q+r:r}};g.d("pv-b",function(){f.d(window,"unload",b())});g.d("duration-send",b());g.d("duration-done",function(){q=v=+new Date;r=0});return h.sa})();
(function(){var b=mt.lang,a=h.m,e=h.load,d={Ub:function(d){if((window._dxt===s||b.e(window._dxt,"Array"))&&"undefined"!==typeof h.c){var g=h.c.Q();e([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(g)].join(""),d)}},mc:function(a){if(b.e(a,"String")||b.e(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.qb=d})();
(function(){function b(a,b,d,e){if(!(a===s||b===s||e===s)){if(""===a)return[b,d,e].join("*");a=String(a).split("!");for(var f,g=x,k=0;k<a.length;k++)if(f=a[k].split("*"),String(b)===f[0]){f[1]=d;f[2]=e;a[k]=f.join("*");g=u;break}g||a.push([b,d,e].join("*"));return a.join("!")}}function a(b){for(var e in b)if({}.hasOwnProperty.call(b,e)){var y=b[e];d.e(y,"Object")||d.e(y,"Array")?a(y):b[e]=String(y)}}var e=mt.url,d=mt.lang,f=mt.s,g=mt.h,m=h.m,l=h.w,p=h.qb,t=h.load,v=h.ra,q=h.Z,r=q.X,k={V:[],ka:0,Ra:x,
B:{Fa:"",page:""},init:function(){k.j=0;q.init();l.d("pv-b",function(){k.rb();k.ub()});l.d("pv-d",function(){k.vb();k.B.page=""});l.d("stag-b",function(){h.c.b.api=k.j||k.ka?k.j+"_"+k.ka:"";h.c.b.ct=[decodeURIComponent(v.getData("Hm_ct_"+c.id)||""),k.B.Fa,k.B.page].join("!")});l.d("stag-d",function(){h.c.b.api=0;k.j=0;k.ka=0})},rb:function(){var a=window._hmt||[];if(!a||d.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var n=arguments[b];
d.e(n,"Array")&&(a.cmd[a.id].push(n),"_setAccount"===n[0]&&(1<n.length&&/^[0-9a-f]{32}$/.test(n[1]))&&(n=n[1],a.id=n,a.cmd[n]=a.cmd[n]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},ub:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,e=0,f=b.length;e<f;e++){var g=b[e];d.test(g[0])?k.V.push(g):k.Ba(g)}a.cmd[c.id]={push:k.Ba}},vb:function(){if(0<k.V.length)for(var a=0,b=k.V.length;a<b;a++)k.Ba(k.V[a]);k.V=
w},Ba:function(a){var b=a[0];if(k.hasOwnProperty(b)&&d.e(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(k.j|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],x===a||u===a))k.j|=2,h.c.Pa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){k.j|=4;h.c.b.sn=h.c.Ma();h.c.b.et=0;h.c.b.ep="";h.c.b.vl=g.S()+g.J();h.c.b.kb=0;h.c.wa?(h.c.b.nv=0,h.c.b.st=4):h.c.wa=u;var b=h.c.b.u,d=h.c.b.su;h.c.b.u=m.protocol+"//"+document.location.host+
a[1];k.Ra||(h.c.b.su=document.location.href);h.c.b.p=r(q.D("pageview"));h.c.i();h.c.b.u=b;h.c.b.su=d;h.c.b.p="";h.c.F=+new Date;q.z("pageview")}},_trackEvent:function(a){2<a.length&&(k.j|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.g(a[1])+"*"+d.g(a[2])+(a[3]?"*"+d.g(a[3]):"")+(a[4]?"*"+d.g(a[4]):""),h.c.b.p=r(q.va()),h.c.i(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){k.ka++;for(var f=(h.c.b.cv||"*").split("!"),g=f.length;g<b-1;g++)f.push("*");
f[b-1]=e+"*"+d.g(a[2])+"*"+d.g(a[3]);h.c.b.cv=f.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?v.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):v.ec("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var e=d.g(a[1]);a=d.g(a[2]);if(e!==s&&a!==s){var f=decodeURIComponent(v.getData("Hm_ct_"+c.id)||""),f=b(f,e,1,a);v.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var e=d.g(a[1]);a=d.g(a[2]);if(e!==
s&&a!==s){var f=k.B.Fa,f=b(f,e,2,a);k.B.Fa=f}}},_setPageTag:function(a){if(!(3>a.length)){var e=d.g(a[1]);a=d.g(a[2]);if(e!==s&&a!==s){var f=k.B.page,f=b(f,e,3,a);k.B.page=f}}},_setReferrerOverride:function(a){1<a.length&&(h.c.b.su=a[1].charAt&&"/"===a[1].charAt(0)?m.protocol+"//"+window.location.host+a[1]:a[1],k.Ra=u)},_trackOrder:function(b){b=b[1];d.e(b,"Object")&&(a(b),k.j|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=f.stringify(b),h.c.b.p=r(q.va()),h.c.i(),h.c.b.p="")},_trackMobConv:function(a){if(a=
{webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.j|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];p.Ub();p.mc(a)},_setUserId:function(a){a=a[1];if(a!==s&&(d.fa(a)||d.ya(a))){var b=q.D("user").uid_;if(!(b&&b.value===d.g(String(a)))){var b=h.c.b.p,e=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+d.g(String(a));h.c.i();var f={};f.uid_=a;q.setProperty("user",f,u);h.c.b.p=b;h.c.b.ep=e}}},_clearUserId:function(a){1<a.length&&u===a[1]&&q.z("userId")},_setUserProperty:function(a){a=
a[1];d.e(a,"Object")&&q.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&u===a[1]&&q.z("user")},_setSessionProperty:function(a){a=a[1];d.e(a,"Object")&&q.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&u===a[1]&&q.z("session")},_setPageviewProperty:function(a){a=a[1];d.e(a,"Object")&&q.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&u===a[1]&&q.z("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];d.e(a,"Object")&&q.setProperty("autoEventTracking",
a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&u===a[1]&&q.z("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],x===a||u===a))h.c.Qa=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],x===a||u===a))h.c.T=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):l.I("duration-send");l.I("duration-done")},_require:function(a){1<a.length&&(a=a[1],m.gb.test(e.R(a))&&t(a))},_providePlugin:function(a){if(1<
a.length){var b=window._hmt,e=a[1];a=a[2];if(d.K(m.Sa,e)&&d.e(a,"Function")&&(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]=a,b.A=b.A||[],a=b.A.slice(),e&&a.length&&a[0][1]===e))for(var f=0,g=a.length;f<g;f++){var k=a[f][2]||{};if(b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](k),b.A.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],f=a[2]||{};if(d.K(m.Sa,e))if(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](f);else{b.A=b.A||
[];for(var f=0,g=b.A.length;f<g;f++)if(b.A[f][1]===e)return;b.A.push(a);k._require([w,m.bc+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];d.e(a,"Object")&&(a._iden=b,q.setProperty("customEvent",a));h.c.b.et=7;h.c.b.ep="";h.c.b.p=r(q.D("customEvent"));h.c.i();h.c.b.p="";q.z("customEvent")}}};k.init();h.hb=k;return h.hb})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.b={},this.Qa=this.Pa=u,this.T=k.T,this.Ja=f.fa(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.wa=x,this.init())}var a=mt.url,e=mt.Ya,d=mt.Da,f=mt.lang,g=mt.cookie,m=mt.h,l=mt.sessionStorage,p=mt.s,t=mt.event,v=h.ra,q=h.Z,r=q.X,k=h.m,n=h.load,z=h.w;b.prototype={U:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ga:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},da:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.ga(b,c.dm[d]))return u}else{var e=a.R(b);if(e&&this.U(e,c.dm[d]))return u}return x},Q:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.U(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},ba:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ga(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},Jb:function(){if(!document.referrer)return k.H-k.L>c.vdur?1:4;var b=x;this.da(document.referrer)&&this.da(document.location.href)?b=u:(b=a.R(document.referrer),b=this.U(b||"",document.location.hostname));return b?k.H-k.L>c.vdur?1:4:3},kc:function(){var a,b,d,e,f;k.L=v.getData("Hm_lpvt_"+c.id)||0;13===k.L.length&&(k.L=Math.round(k.L/1E3));b=this.Jb();a=4!==b?1:0;if(d=v.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.H-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.H);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.H,e="",f=1;v.setData("Hm_lvt_"+c.id,d,c.age);v.setData("Hm_lpvt_"+c.id,k.H);d=g.Xb(this.Q(),this.ba());if(0===c.nv&&this.da(document.location.href)&&(""===document.referrer||this.da(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},Wa:function(){for(var a=[],b=this.b.et,d=+new Date,e=0,f=k.Za.length;e<f;e++){var g=k.Za[e],
l=this.b[g];"undefined"!==typeof l&&""!==l&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(l))}switch(b){case 0:this.b.rt&&a.push("rt="+encodeURIComponent(this.b.rt));break;case 5:a.push("_lpt="+this.F);a.push("_ct="+d);break;case 6:a.push("_lpt="+this.F);a.push("_ct="+d);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},lc:function(){this.kc();this.b.si=c.id;this.b.sn=this.Ma();this.b.su=document.referrer;
this.b.hh=window.location.hash;this.b.ds=m.fc;this.b.cl=m.colorDepth+"-bit";this.b.ln=String(m.language).toLowerCase();this.b.ja=m.javaEnabled?1:0;this.b.ck=m.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=d.Lb();this.b.v="1.2.61";this.b.cv=decodeURIComponent(v.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=m.S()+m.J();var b=document.location.href;this.b.cm=a.o(b,k.Qb)||"";this.b.cp=a.o(b,k.Rb)||a.o(b,k.qc)||"";this.b.cw=a.o(b,k.Pb)||a.o(b,k.sc)||"";this.b.ci=
a.o(b,k.Nb)||a.o(b,k.pc)||"";this.b.cf=a.o(b,k.Sb)||a.o(b,k.rc)||"";this.b.cu=a.o(b,k.Ob)||a.o(b,k.oc)||""},init:function(){try{this.lc(),0===this.b.nv?this.jc():this.Ka(),h.c=this,this.lb(),this.jb(),z.I("pv-b"),this.ic()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));e.log(k.ha+"//"+k.Ca+"?"+b.join("&"))}},ic:function(){function a(){z.I("pv-d")}this.Pa?(this.wa=u,this.b.et=
0,this.b.ep="",this.b.p=r(q.D("pageview")),this.b.vl=m.S()+m.J(),this.i(a),this.b.p=""):a();this.F=+new Date;q.z("pageview")},i:function(a){if(this.Qa){var b=this;b.b.rnd=Math.round(Math.random()*k.M);z.I("stag-b");var d=k.ha+"//"+k.Ca+"?"+b.Wa();z.I("stag-d");b.fb(d);e.log(d,function(d){b.Va(d);f.e(a,"Function")&&a.call(b)})}},lb:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.R(document.referrer)===k.$a?1:0,f=a.o(b,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);b&&(d.test(b)&&
e&&g)&&(this.b.rnd=Math.round(Math.random()*k.M),b=document.createElement("script"),b.setAttribute("type","text/javascript"),b.setAttribute("charset","utf-8"),b.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},jb:function(){if(window.postMessage&&window.self!==window.parent){var b=this;t.d(window,"message",function(d){if(a.R(d.origin)===k.$a){d=d.data||{};var e=d.jn||"",f=/^customevent$/.test(e);if(RegExp(c.id).test(d.sd||
"")&&f)b.b.rnd=Math.round(Math.random()*k.M),n(k.protocol+"//"+c.js+e+".js?"+b.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},fb:function(a){var b;try{b=p.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+c.id,p.stringify(b))},Va:function(a){var b;try{b=p.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=
a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,p.stringify(b)):this.Ka()}},Ka:function(){l.remove("Hm_unsent_"+c.id)},jc:function(){var a=this,b;try{b=p.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var f=function(b){e.log(k.ha+"//"+b,function(b){a.Va(b)})},g=0;g<b.length;g++)f(b[g])},Ma:function(){return Math.round(+new Date/1E3)%65535}};return new b})();
var B=h.m,C=h.load;if(c.apps){var D=[B.protocol,"//ers.baidu.com/app/s.js?"];D.push(c.apps);C(D.join(""))}(function(){var b=mt.event,a=mt.lang,e=h.m;if(c.kbtrk&&"undefined"!==typeof h.c){h.c.b.kb=a.ya(h.c.b.kb)?h.c.b.kb:0;var d=function(){h.c.b.et=85;h.c.b.ep=h.c.b.kb;h.c.i()};b.d(document,"keyup",function(){h.c.b.kb++});b.d(window,"unload",function(){d()});setInterval(d,e.Yb)}})();var E=h.m,F=h.load;c.pt&&F([E.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
var H=h.m,I=h.load;c.lxb&&I([H.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var J=h.load,K=h.m.protocol;if(c.qiao){for(var L=[K+"//goutong.baidu.com/site/"],M=c.id,N=5381,O=M.length,P=0;P<O;P++)N=(33*N+Number(M.charCodeAt(P)))%4294967296;2147483648<N&&(N-=2147483648);L.push(N%1E3+"/");L.push(c.id+"/b.js");L.push("?siteId="+c.qiao);J(L.join(""))}
(function(){var b=mt.h,a=mt.lang,e=mt.event,d=mt.s;if("undefined"!==typeof h.c&&(c.med||(!b.xa||7<b.Eb())&&c.cvcc)){var f,g,m,l,p=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},t=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===x)return x},v=function(b,e){var g={};g.n=f;g.t="clk";g.v=b;if(e){var k=e.getAttribute("href"),l=e.getAttribute("onclick")?""+e.getAttribute("onclick"):w,p=e.getAttribute("id")||"";m.test(k)?(g.sn=
"mediate",g.snv=k):a.e(l,"String")&&m.test(l)&&(g.sn="wrap",g.snv=l);g.id=p}h.c.b.et=86;h.c.b.ep=d.stringify(g);h.c.i();for(g=+new Date;400>=+new Date-g;);};if(c.med)g="/zoosnet",f="swt",m=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,l={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(m.test(e)||m.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){g="/other-comm";f="other";m=c.cvcc.q||s;var q=c.cvcc.id||s;l={click:function(){for(var a=[],b=p(document.getElementsByTagName("a")),b=[].concat.apply(b,p(document.getElementsByTagName("area"))),b=[].concat.apply(b,p(document.getElementsByTagName("img"))),d,e,f,g=0,k=b.length;g<k;g++)d=b[g],m!==s?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),q?(d=d.getAttribute("id"),(m.test(e)||
m.test(f)||q.test(d))&&a.push(b[g])):(m.test(e)||m.test(f))&&a.push(b[g])):q!==s&&(d=d.getAttribute("id"),q.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof l&&"undefined"!==typeof m){var r;g+=/\/$/.test(g)?"":"/";var k=function(b,d){if(r===d)return v(g+b,d),x;if(a.e(d,"Array")||a.e(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(r===d[e])return v(g+b+"/"+(e+1),d[e]),x};e.d(document,"mousedown",function(b){b=b||window.event;r=b.target||b.srcElement;var d={};for(t(l,function(b,e){d[b]=a.e(e,
"Function")?e():document.getElementById(e)});r&&r!==document&&t(d,k)!==x;)r=r.parentNode})}}})();(function(){var b=mt.f,a=mt.lang,e=mt.event,d=mt.s;if("undefined"!==typeof h.c&&a.e(c.cvcf,"Array")&&0<c.cvcf.length){var f={bb:function(){for(var a=c.cvcf.length,d,l=0;l<a;l++)(d=b.aa(decodeURIComponent(c.cvcf[l])))&&e.d(d,"click",f.$())},$:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=d.stringify(a);h.c.i()}}};b.Ta(function(){f.bb()})}})();
(function(){var b=mt.event,a=mt.s;if(c.med&&"undefined"!==typeof h.c){var e={n:"anti",sb:0,kb:0,clk:0},d=function(){h.c.b.et=86;h.c.b.ep=a.stringify(e);h.c.i()};b.d(document,"click",function(){e.clk++});b.d(document,"keyup",function(){e.kb=1});b.d(window,"scroll",function(){e.sb++});b.d(window,"load",function(){setTimeout(d,5E3)})}})();c.spa!==s&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]));})();
